// ========================================
// EYE VISION OPTICS - COMPLETE PRODUCTS
// LOCAL IMAGES PATH (images folder ke andar)
// ========================================

const products = [
    // ========== FEATURED PRODUCTS ==========
    {
        id: 1,
        name: "Ray-Ban Classic Wayfarer",
        price: 3000,
        category: "Eyeglasses",
        subCategory: "Men",
        rating: 4.8,
        brand: "Ray-Ban",
        // LOCAL IMAGE PATH - images/featured/ folder mein
        image: "images/featured/rayban-wayfarer.jpg",
        images: [
            "images/featured/rayban-wayfarer.jpg",
            "images/eyeglasses/men/rayban-side.jpg",
            "images/eyeglasses/men/rayban-back.jpg"
        ],
        description: "Classic Wayfarer design. Premium acetate frame. UV protection.",
        colors: ["Black", "Tortoise", "Brown"],
        sizes: ["Small", "Medium", "Large"],
        inStock: true,
        featured: true
    },
    {
        id: 2,
        name: "images/featured/oakley-holbrook",
        price: 4349,
        category: "Eyeglasses",
        subCategory: "Men",
        rating: 4.9,
        brand: "Oakley",
        image: "images/featured/oakley-holbrook.jpg",
        images: ["images/featured/oakley-holbrook.jpg", "images/eyeglasses/men/oakley-side.jpg"],
        description: "Sporty square frame. Lightweight and durable.",
        colors: ["Matte Black", "Gunmetal", "Silver"],
        sizes: ["Medium", "Large"],
        inStock: true,
        featured: true
    },
    {
        id: 3,
        name: "Gucci Cat-Eye Glasses",
        price: 4699,
        category: "Eyeglasses",
        subCategory: "Women",
        rating: 4.9,
        brand: "Gucci",
        image: "images/featured/gucci-cateye.jpg",
        images: ["images/featured/gucci-cateye.jpg", "images/eyeglasses/women/gucci-side.jpg"],
        description: "Trendy cat-eye frame. Premium acetate. Elegant design.",
        colors: ["Black", "Tortoise", "Maroon", "Rose Gold"],
        sizes: ["Small", "Medium"],
        inStock: true,
        featured: true
    },
    {
        id: 4,
        name: "Dior Oversized",
        price: 3999,
        category: "Eyeglasses",
        subCategory: "Women",
        rating: 4.8,
        brand: "Dior",
        image: "images/featured/dior-oversized.jpg",
        images: ["images/featured/dior-oversized.jpg", "images/eyeglasses/women/dior-side.jpg"],
        description: "Oversized glamorous frame. Statement piece.",
        colors: ["Black", "Cream", "Rose", "White"],
        sizes: ["Medium", "Large"],
        inStock: true,
        featured: true
    },
    {
        id: 5,
        name: "Disney Kids Glasses",
        price: 2999,
        category: "Eyeglasses",
        subCategory: "Kids",
        rating: 4.5,
        brand: "Disney",
        image: "images/featured/disney-kids.jpg",
        images: ["images/featured/disney-kids.jpg", "images/eyeglasses/kids/disney-side.jpg"],
        description: "Colorful frames for kids. Flexible and durable.",
        colors: ["Blue", "Red", "Pink", "Green"],
        sizes: ["Small", "Medium"],
        inStock: true,
        featured: true
    },
    {
        id: 6,
        name: "Ray-Ban Aviator",
        price: 2999,
        category: "Sunglasses",
        subCategory: "Unisex",
        rating: 4.9,
        brand: "Ray-Ban",
        image: "images/featured/aviator-sunglass.jpg",
        images: ["images/featured/aviator-sunglass.jpg", "images/sunglasses/rayban-aviator-side.jpg"],
        description: "Classic aviator sunglasses. UV400 protection.",
        colors: ["Gold Frame", "Black Frame", "Silver Frame"],
        sizes: ["One Size"],
        inStock: true,
        featured: true
    },
    {
        id: 7,
        name: "Oakley Holbrook",
        price: 11999,
        category: "Sunglasses",
        subCategory: "Unisex",
        rating: 4.8,
        brand: "Oakley",
        image: "images/featured/oakley-holbrook.jpg",
        images: ["images/featured/oakley-holbrook.jpg", "images/sunglasses/oakley-holbrook-side.jpg"],
        description: "Sporty lifestyle sunglasses. Prizm lenses.",
        colors: ["Matte Black", "Polished Black", "Woodgrain"],
        sizes: ["One Size"],
        inStock: true,
        featured: true
    },
    {
        id: 8,
        name: "Cat-Eye Sunglasses",
        price: 4499,
        category: "Sunglasses",
        subCategory: "Women",
        rating: 4.6,
        brand: "Glamour",
        image: "images/featured/cateye-sunglass.jpg",
        images: ["images/featured/cateye-sunglass.jpg", "images/sunglasses/cateye-side.jpg"],
        description: "Trendy cat-eye design for women.",
        colors: ["Black", "Tortoise", "Maroon"],
        sizes: ["One Size"],
        inStock: true,
        featured: true
    },
    {
        id: 9,
        name: "Blue Cut Anti-Glare",
        price: 1999,
        category: "Lenses",
        subCategory: "Accessories",
        rating: 4.6,
        brand: "ZEISS",
        image: "images/featured/bluecut-lens.jpg",
        images: ["images/featured/bluecut-lens.jpg", "images/lenses/bluecut-detail.jpg"],
        description: "Premium blue cut lenses for computer use.",
        colors: ["Clear", "Yellow"],
        sizes: ["Standard"],
        inStock: true,
        featured: true
    },
    {
        id: 10,
        name: "Transition Lenses",
        price: 3999,
        category: "Lenses",
        subCategory: "Accessories",
        rating: 4.8,
        brand: "Transitions",
        image: "images/featured/transition-lens.jpg",
        images: ["images/featured/transition-lens.jpg", "images/lenses/transition-detail.jpg"],
        description: "Lenses that darken in sunlight.",
        colors: ["Clear to Grey", "Clear to Brown"],
        sizes: ["Standard"],
        inStock: true,
        featured: true
    },

    // ========== MEN EYEGLASSES (More) ==========
    {
        id: 11,
        name: "Tom Ford Round Metal",
        price: 15999,
        category: "Eyeglasses",
        subCategory: "Men",
        rating: 4.7,
        brand: "Tom Ford",
        image: "images/eyeglasses/men/tomford-round.jpg",
        colors: ["Gold", "Silver", "Rose Gold"],
        sizes: ["Medium"],
        inStock: true,
        featured: false
    },
    {
        id: 12,
        name: "Prada Rectangular",
        price: 18999,
        category: "Eyeglasses",
        subCategory: "Men",
        rating: 4.8,
        brand: "Prada",
        image: "images/eyeglasses/men/prada-rectangular.jpg",
        colors: ["Black", "Navy", "Brown"],
        sizes: ["Medium", "Large"],
        inStock: true,
        featured: false
    },

    // ========== WOMEN EYEGLASSES (More) ==========
    {
        id: 13,
        name: "Versace Butterfly",
        price: 16999,
        category: "Eyeglasses",
        subCategory: "Women",
        rating: 4.7,
        brand: "Versace",
        image: "images/eyeglasses/women/versace-butterfly.jpg",
        colors: ["Gold", "Silver", "Black", "Pink"],
        sizes: ["Small", "Medium"],
        inStock: true,
        featured: false
    },
    {
        id: 14,
        name: "Chanel Classic",
        price: 22999,
        category: "Eyeglasses",
        subCategory: "Women",
        rating: 5.0,
        brand: "Chanel",
        image: "images/eyeglasses/women/chanel-classic.jpg",
        colors: ["Black", "Beige", "White", "Navy"],
        sizes: ["Medium"],
        inStock: true,
        featured: false
    },
    {
        id: 15,
        name: "Fendi Round Frame",
        price: 15999,
        category: "Eyeglasses",
        subCategory: "Women",
        rating: 4.6,
        brand: "Fendi",
        image: "images/eyeglasses/women/fendi-round.jpg",
        colors: ["Gold", "Silver", "Black"],
        sizes: ["Small", "Medium"],
        inStock: true,
        featured: false
    },

    // ========== KIDS EYEGLASSES (More) ==========
    {
        id: 16,
        name: "Flexi Kids Blue Block",
        price: 2499,
        category: "Eyeglasses",
        subCategory: "Kids",
        rating: 4.4,
        brand: "Flexi",
        image: "images/eyeglasses/kids/flexi-blue.jpg",
        colors: ["Blue", "Green", "Purple"],
        sizes: ["Small"],
        inStock: true,
        featured: false
    },
    {
        id: 17,
        name: "Nike Kids Sport",
        price: 3999,
        category: "Eyeglasses",
        subCategory: "Kids",
        rating: 4.6,
        brand: "Nike",
        image: "images/eyeglasses/kids/nike-sport.jpg",
        colors: ["Black/Red", "Blue/White", "Pink/White"],
        sizes: ["Small", "Medium"],
        inStock: true,
        featured: false
    },

    // ========== MORE SUNGLASSES ==========
    {
        id: 18,
        name: "Polarized Sports",
        price: 4999,
        category: "Sunglasses",
        subCategory: "Unisex",
        rating: 4.7,
        brand: "SportShield",
        image: "images/sunglasses/polarized-sports.jpg",
        colors: ["Matte Black", "Blue", "Red"],
        sizes: ["One Size"],
        inStock: true,
        featured: false
    },
    {
        id: 19,
        name: "Vintage Round",
        price: 3499,
        category: "Sunglasses",
        subCategory: "Unisex",
        rating: 4.5,
        brand: "Vintage",
        image: "images/sunglasses/vintage-round.jpg",
        colors: ["Gold", "Silver", "Black"],
        sizes: ["One Size"],
        inStock: true,
        featured: false
    },
    {
        id: 20,
        name: "Wayfarer Classic",
        price: 7999,
        category: "Sunglasses",
        subCategory: "Unisex",
        rating: 4.8,
        brand: "Ray-Ban",
        image: "images/sunglasses/wayfarer-classic.jpg",
        colors: ["Black", "Tortoise", "Brown"],
        sizes: ["One Size"],
        inStock: true,
        featured: false
    },

    // ========== MORE LENSES ==========
    {
        id: 21,
        name: "Polarized Lenses",
        price: 2999,
        category: "Lenses",
        subCategory: "Accessories",
        rating: 4.7,
        brand: "PolarTech",
        image: "images/lenses/polarized-lens.jpg",
        colors: ["Grey", "Brown", "Green"],
        sizes: ["Standard"],
        inStock: true,
        featured: false
    },
    {
        id: 22,
        name: "High Index Thin",
        price: 4999,
        category: "Lenses",
        subCategory: "Accessories",
        rating: 4.5,
        brand: "ZEISS",
        image: "images/lenses/highindex-lens.jpg",
        colors: ["Clear"],
        sizes: ["Standard"],
        inStock: true,
        featured: false
    },
    {
        id: 23,
        name: "Progressive Lenses",
        price: 7999,
        category: "Lenses",
        subCategory: "Accessories",
        rating: 4.8,
        brand: "ZEISS",
        image: "images/lenses/progressive-lens.jpg",
        colors: ["Clear"],
        sizes: ["Standard"],
        inStock: true,
        featured: false
    },
    {
        id: 24,
        name: "Anti-Fog Lenses",
        price: 2499,
        category: "Lenses",
        subCategory: "Accessories",
        rating: 4.4,
        brand: "OptiClear",
        image: "images/lenses/antifog-lens.jpg",
        colors: ["Clear"],
        sizes: ["Standard"],
        inStock: true,
        featured: false
    }
];

window.products = products;
console.log("✅ Products loaded with local images! Total:", products.length);