// ========================================
// EYE VISION OPTICS - COMPLETE PRODUCTS
// REAL PRODUCT IMAGES FROM UNSPLASH
// Total: 24 Products with Real Images
// ========================================

const products = [
    // ========== MEN EYEGLASSES (6 Products) ==========
    {
        id: 1,
        name: "Ray-Ban Classic Wayfarer",
        price: 8999,
        category: "Eyeglasses",
        subCategory: "Men",
        rating: 4.8,
        brand: "Ray-Ban",
        image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=400&fit=crop"],
        description: "Classic Wayfarer design. Premium acetate frame. UV protection. Timeless style since 1956.",
        colors: ["Black", "Tortoise", "Brown"],
        sizes: ["Small", "Medium", "Large"],
        inStock: true,
        featured: true
    },
    {
        id: 2,
        name: "Oakley Square Frame",
        price: 12999,
        category: "Eyeglasses",
        subCategory: "Men",
        rating: 4.9,
        brand: "Oakley",
        image: "https://images.unsplash.com/photo-1532245614115-b6c742b13b88?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1532245614115-b6c742b13b88?w=600&h=400&fit=crop"],
        description: "Sporty square frame. Lightweight and durable. Perfect for active lifestyle.",
        colors: ["Matte Black", "Gunmetal", "Silver"],
        sizes: ["Medium", "Large"],
        inStock: true,
        featured: true
    },
    {
        id: 3,
        name: "Tom Ford Round Metal",
        price: 15999,
        category: "Eyeglasses",
        subCategory: "Men",
        rating: 4.7,
        brand: "Tom Ford",
        image: "https://images.unsplash.com/photo-1584382296087-50e3e219ad1b?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1584382296087-50e3e219ad1b?w=600&h=400&fit=crop"],
        description: "Premium round metal frame. Luxury design. Italian craftsmanship.",
        colors: ["Gold", "Silver", "Rose Gold"],
        sizes: ["Medium"],
        inStock: true,
        featured: false
    },
    {
        id: 4,
        name: "Prada Rectangular",
        price: 18999,
        category: "Eyeglasses",
        subCategory: "Men",
        rating: 4.8,
        brand: "Prada",
        image: "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=600&h=400&fit=crop"],
        description: "Designer rectangular frame. Italian craftsmanship. Luxury style statement.",
        colors: ["Black", "Navy", "Brown"],
        sizes: ["Medium", "Large"],
        inStock: true,
        featured: false
    },
    {
        id: 5,
        name: "Police Blue Block",
        price: 7999,
        category: "Eyeglasses",
        subCategory: "Men",
        rating: 4.6,
        brand: "Police",
        image: "https://images.unsplash.com/photo-1577803645778-772f576adc8a?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1577803645778-772f576adc8a?w=600&h=400&fit=crop"],
        description: "Blue light blocking glasses. Reduces eye strain. Perfect for computer users.",
        colors: ["Black", "Blue", "Grey"],
        sizes: ["Medium", "Large"],
        inStock: true,
        featured: false
    },
    {
        id: 6,
        name: "Diesel Bold Frame",
        price: 10999,
        category: "Eyeglasses",
        subCategory: "Men",
        rating: 4.5,
        brand: "Diesel",
        image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&h=400&fit=crop"],
        description: "Bold and edgy design. Makes a strong fashion statement.",
        colors: ["Black", "Red", "Blue"],
        sizes: ["Large"],
        inStock: true,
        featured: false
    },
    
    // ========== WOMEN EYEGLASSES (6 Products) ==========
    {
        id: 7,
        name: "Gucci Cat-Eye Glasses",
        price: 19999,
        category: "Eyeglasses",
        subCategory: "Women",
        rating: 4.9,
        brand: "Gucci",
        image: "https://images.unsplash.com/photo-1584382296087-50e3e219ad1b?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1584382296087-50e3e219ad1b?w=600&h=400&fit=crop"],
        description: "Trendy cat-eye frame. Premium acetate. Elegant design for women.",
        colors: ["Black", "Tortoise", "Maroon", "Rose Gold"],
        sizes: ["Small", "Medium"],
        inStock: true,
        featured: true
    },
    {
        id: 8,
        name: "Dior Oversized",
        price: 17999,
        category: "Eyeglasses",
        subCategory: "Women",
        rating: 4.8,
        brand: "Dior",
        image: "https://images.unsplash.com/photo-1532245614115-b6c742b13b88?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1532245614115-b6c742b13b88?w=600&h=400&fit=crop"],
        description: "Oversized glamorous frame. Statement piece for fashion-forward women.",
        colors: ["Black", "Cream", "Rose", "White"],
        sizes: ["Medium", "Large"],
        inStock: true,
        featured: true
    },
    {
        id: 9,
        name: "Versace Butterfly",
        price: 16999,
        category: "Eyeglasses",
        subCategory: "Women",
        rating: 4.7,
        brand: "Versace",
        image: "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=600&h=400&fit=crop"],
        description: "Butterfly shaped frame. Elegant and sophisticated design.",
        colors: ["Gold", "Silver", "Black", "Pink"],
        sizes: ["Small", "Medium"],
        inStock: true,
        featured: false
    },
    {
        id: 10,
        name: "Chanel Classic",
        price: 22999,
        category: "Eyeglasses",
        subCategory: "Women",
        rating: 5.0,
        brand: "Chanel",
        image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=400&fit=crop"],
        description: "Classic Chanel design. Timeless elegance. Premium quality.",
        colors: ["Black", "Beige", "White", "Navy"],
        sizes: ["Medium"],
        inStock: true,
        featured: false
    },
    {
        id: 11,
        name: "Fendi Round Frame",
        price: 15999,
        category: "Eyeglasses",
        subCategory: "Women",
        rating: 4.6,
        brand: "Fendi",
        image: "https://images.unsplash.com/photo-1577803645778-772f576adc8a?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1577803645778-772f576adc8a?w=600&h=400&fit=crop"],
        description: "Vintage round frame. Retro chic style.",
        colors: ["Gold", "Silver", "Black"],
        sizes: ["Small", "Medium"],
        inStock: true,
        featured: false
    },
    {
        id: 12,
        name: "Burberry Check Frame",
        price: 18999,
        category: "Eyeglasses",
        subCategory: "Women",
        rating: 4.7,
        brand: "Burberry",
        image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&h=400&fit=crop"],
        description: "Iconic Burberry check pattern. British luxury.",
        colors: ["Brown", "Black", "Beige"],
        sizes: ["Medium", "Large"],
        inStock: true,
        featured: false
    },
    
    // ========== KIDS EYEGLASSES (4 Products) ==========
    {
        id: 13,
        name: "Disney Kids Glasses",
        price: 2999,
        category: "Eyeglasses",
        subCategory: "Kids",
        rating: 4.5,
        brand: "Disney",
        image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&h=400&fit=crop"],
        description: "Colorful frames for kids. Flexible and durable. Safe for children.",
        colors: ["Blue", "Red", "Pink", "Green"],
        sizes: ["Small", "Medium"],
        inStock: true,
        featured: true
    },
    {
        id: 14,
        name: "Flexi Kids Blue Block",
        price: 2499,
        category: "Eyeglasses",
        subCategory: "Kids",
        rating: 4.4,
        brand: "Flexi",
        image: "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=600&h=400&fit=crop"],
        description: "Blue light blocking glasses for children. Protects eyes from screens.",
        colors: ["Blue", "Green", "Purple"],
        sizes: ["Small"],
        inStock: true,
        featured: false
    },
    {
        id: 15,
        name: "Nike Kids Sport",
        price: 3999,
        category: "Eyeglasses",
        subCategory: "Kids",
        rating: 4.6,
        brand: "Nike",
        image: "https://images.unsplash.com/photo-1532245614115-b6c742b13b88?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1532245614115-b6c742b13b88?w=600&h=400&fit=crop"],
        description: "Sports glasses for active kids. Durable and flexible.",
        colors: ["Black/Red", "Blue/White", "Pink/White"],
        sizes: ["Small", "Medium"],
        inStock: true,
        featured: false
    },
    {
        id: 16,
        name: "Cartoon Character Frames",
        price: 1999,
        category: "Eyeglasses",
        subCategory: "Kids",
        rating: 4.3,
        brand: "Cartoon",
        image: "https://images.unsplash.com/photo-1577803645778-772f576adc8a?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1577803645778-772f576adc8a?w=600&h=400&fit=crop"],
        description: "Fun cartoon character frames that kids love.",
        colors: ["Red", "Blue", "Pink", "Yellow"],
        sizes: ["Small"],
        inStock: true,
        featured: false
    },
    
    // ========== SUNGLASSES (6 Products) ==========
    {
        id: 17,
        name: "Ray-Ban Aviator",
        price: 9999,
        category: "Sunglasses",
        subCategory: "Unisex",
        rating: 4.9,
        brand: "Ray-Ban",
        image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&h=400&fit=crop"],
        description: "Classic aviator sunglasses. UV400 protection. Iconic style since 1937.",
        colors: ["Gold Frame", "Black Frame", "Silver Frame"],
        sizes: ["One Size"],
        inStock: true,
        featured: true
    },
    {
        id: 18,
        name: "Oakley Holbrook",
        price: 11999,
        category: "Sunglasses",
        subCategory: "Unisex",
        rating: 4.8,
        brand: "Oakley",
        image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=400&fit=crop"],
        description: "Sporty lifestyle sunglasses. Prizm lenses for enhanced color.",
        colors: ["Matte Black", "Polished Black", "Woodgrain"],
        sizes: ["One Size"],
        inStock: true,
        featured: true
    },
    {
        id: 19,
        name: "Polarized Sports",
        price: 4999,
        category: "Sunglasses",
        subCategory: "Unisex",
        rating: 4.7,
        brand: "SportShield",
        image: "https://images.unsplash.com/photo-1532245614115-b6c742b13b88?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1532245614115-b6c742b13b88?w=600&h=400&fit=crop"],
        description: "Polarized sports sunglasses for outdoor activities. Reduces glare.",
        colors: ["Matte Black", "Blue", "Red"],
        sizes: ["One Size"],
        inStock: true,
        featured: false
    },
    {
        id: 20,
        name: "Vintage Round Sunglasses",
        price: 3499,
        category: "Sunglasses",
        subCategory: "Unisex",
        rating: 4.5,
        brand: "Vintage",
        image: "https://images.unsplash.com/photo-1584382296087-50e3e219ad1b?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1584382296087-50e3e219ad1b?w=600&h=400&fit=crop"],
        description: "Retro round frame sunglasses. Bohemian style.",
        colors: ["Gold", "Silver", "Black"],
        sizes: ["One Size"],
        inStock: true,
        featured: false
    },
    {
        id: 21,
        name: "Wayfarer Classic",
        price: 7999,
        category: "Sunglasses",
        subCategory: "Unisex",
        rating: 4.8,
        brand: "Ray-Ban",
        image: "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=600&h=400&fit=crop"],
        description: "Original Wayfarer design. Iconic style. Timeless appeal.",
        colors: ["Black", "Tortoise", "Brown"],
        sizes: ["One Size"],
        inStock: true,
        featured: false
    },
    {
        id: 22,
        name: "Cat-Eye Sunglasses",
        price: 4499,
        category: "Sunglasses",
        subCategory: "Women",
        rating: 4.6,
        brand: "Glamour",
        image: "https://images.unsplash.com/photo-1577803645778-772f576adc8a?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1577803645778-772f576adc8a?w=600&h=400&fit=crop"],
        description: "Trendy cat-eye design for women. Vintage glamour.",
        colors: ["Black", "Tortoise", "Maroon"],
        sizes: ["One Size"],
        inStock: true,
        featured: true
    },
    
    // ========== LENSES (6 Products) ==========
    {
        id: 23,
        name: "Blue Cut Anti-Glare Lenses",
        price: 1999,
        category: "Lenses",
        subCategory: "Accessories",
        rating: 4.6,
        brand: "ZEISS",
        image: "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=600&h=400&fit=crop"],
        description: "Premium blue cut lenses for computer use. Reduces eye strain and headaches.",
        colors: ["Clear", "Yellow"],
        sizes: ["Standard"],
        inStock: true,
        featured: true
    },
    {
        id: 24,
        name: "Photochromic Transition Lenses",
        price: 3999,
        category: "Lenses",
        subCategory: "Accessories",
        rating: 4.8,
        brand: "Transitions",
        image: "https://images.unsplash.com/photo-1532245614115-b6c742b13b88?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1532245614115-b6c742b13b88?w=600&h=400&fit=crop"],
        description: "Lenses that darken in sunlight. Perfect for indoors and outdoors.",
        colors: ["Clear to Grey", "Clear to Brown"],
        sizes: ["Standard"],
        inStock: true,
        featured: true
    },
    {
        id: 25,
        name: "Polarized Lenses",
        price: 2999,
        category: "Lenses",
        subCategory: "Accessories",
        rating: 4.7,
        brand: "PolarTech",
        image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=400&fit=crop"],
        description: "Reduce glare from water, snow, and roads. Perfect for driving.",
        colors: ["Grey", "Brown", "Green"],
        sizes: ["Standard"],
        inStock: true,
        featured: false
    },
    {
        id: 26,
        name: "High Index Thin Lenses",
        price: 4999,
        category: "Lenses",
        subCategory: "Accessories",
        rating: 4.5,
        brand: "ZEISS",
        image: "https://images.unsplash.com/photo-1584382296087-50e3e219ad1b?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1584382296087-50e3e219ad1b?w=600&h=400&fit=crop"],
        description: "Thin and lightweight for high prescriptions. Maximum comfort.",
        colors: ["Clear"],
        sizes: ["Standard"],
        inStock: true,
        featured: false
    },
    {
        id: 27,
        name: "Progressive Multifocal Lenses",
        price: 7999,
        category: "Lenses",
        subCategory: "Accessories",
        rating: 4.8,
        brand: "ZEISS",
        image: "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=600&h=400&fit=crop"],
        description: "No-line multifocal lenses for reading and distance. Smooth transition.",
        colors: ["Clear"],
        sizes: ["Standard"],
        inStock: true,
        featured: false
    },
    {
        id: 28,
        name: "Anti-Fog Coating Lenses",
        price: 2499,
        category: "Lenses",
        subCategory: "Accessories",
        rating: 4.4,
        brand: "OptiClear",
        image: "https://images.unsplash.com/photo-1532245614115-b6c742b13b88?w=400&h=300&fit=crop",
        images: ["https://images.unsplash.com/photo-1532245614115-b6c742b13b88?w=600&h=400&fit=crop"],
        description: "Prevent fogging in masks and cold weather. Crystal clear vision.",
        colors: ["Clear"],
        sizes: ["Standard"],
        inStock: true,
        featured: false
    }
];

// Make products available globally
window.products = products;

// Console log to verify
console.log("✅ Products loaded successfully!");
console.log("📊 Total Products:", products.length);
console.log("👓 Eyeglasses:", products.filter(p => p.category === "Eyeglasses").length);
console.log("👨 Men:", products.filter(p => p.subCategory === "Men").length);
console.log("👩 Women:", products.filter(p => p.subCategory === "Women").length);
console.log("👶 Kids:", products.filter(p => p.subCategory === "Kids").length);
console.log("🕶️ Sunglasses:", products.filter(p => p.category === "Sunglasses").length);
console.log("💎 Lenses:", products.filter(p => p.category === "Lenses").length);
console.log("⭐ Featured Products:", products.filter(p => p.featured === true).length);